### ISSUE TITLE
Is there a tutorial about how to create a classifier?

### ISSUE THREAD

**Issue by zacharylau10** [yanailab/moana#2]
Hi,
    I've read the tutorial documents and re run it at local, but I didn't see any information about how to create the classifier. If the script about producing PBMC classifier is available, could you update it to repository? Thank you!

**Comment by pavlin-policar** [comment]
@zacharylau10 Did you ever figure out how to fit your own classifiers?

**Comment by pavlin-policar** [comment]
I seem to have found a `.fit` method in [moana/classify/cell_type.py](https://github.com/yanailab/moana/blob/master/moana/classify/cell_type.py#L249). Hopefully this is what I'm looking for.
